### ISSUE TITLE
Alpha Crash

### ISSUE THREAD

**Issue by unusualbob** [indianpoptart/RadioControl#19]
Release: v3.0.1 - Alpha5
Device: Sony Xperia Z3C
OS: 4.4.4

I've got an instant crash as soon as I open up the application. Unfortunately there is no report crash, likely because it is installed via side-load rather than store. I'll see if I can capture a stacktrace at some point via adb. I'm a bit out of practice as I haven't done android dev in a few years now, any recommendations?

**Comment by indianpoptart** [comment]
I know the problem, it's with api19 and material design. KitKat also allows setting airplane mode without root. I found a solution for your problem

https://github.com/eliotstocker/Radio-Disable

Let me know it it works for you

**Comment by unusualbob** [comment]
I'll test that when I get home, I do have root though.

**Comment by unusualbob** [comment]
Yep, that works perfectly. Thanks for the pointer. You can close this if you want, or you can leave it open if you'd still like to address the issue in your app as well.

**Comment by indianpoptart** [comment]
No problem. Probably won't make a fix, as the app is intended for 5.0+. If I do make a fix, it will probably be a different app altogether
