### ISSUE TITLE
Uninstall issue - now airplane mode only controls cell radio

### ISSUE THREAD

**Issue by ascendotuum** [indianpoptart/RadioControl#28]
After uninstalling the app, when I enable airplane mode it only disables the cellular radio. Bluetooth and WiFi remain unchanged.

**Comment by indianpoptart** [comment]
Hey,

This can be fixed if you reinstall the app, join a wifi network, wait for the app to turn on airplane mode. Then, turn off wifi, wait for the app to turn off airplane mode, then you can uninstall the app and airplane mode should work perfectly.

-Nikhil

**Comment by indianpoptart** [comment]
For the next release:
- Add setting to restore original airplane mode toggles

**Comment by ascendotuum** [comment]
Thanks for the update, I ended up doing a clean reinstall for other reasons so it's working for me now.

**Comment by indianpoptart** [comment]
Sounds good, glad it's working
