### ISSUE TITLE
VT PUP alerts

### ISSUE THREAD

**Issue by IzzySoft** [indianpoptart/RadioControl#63]
Since v5.0 (when you introduced all those Analytics and Firebase) the `.apk` raises some alerts at VirusTotal: [v5.0](https://www.virustotal.com/de/file/b9cfcf9e9104baa99dcef1f39d754b3a5b405f7aa64cfbf6c2bf30e04d81adde/analysis/1516559949/) and [v5.0.1](https://www.virustotal.com/de/file/f48b60a9bf14b7401b73332d2213008f8298c386e6dabc5af9066512379df1f6/analysis/1517251180/). As the library count increased by almost factor 2 with v5, it could of course also be some other 3rd party element responsible. Could you please have a look?

**Comment by indianpoptart** [comment]
Sure thing! I'm not quite sure why it would be doing that, but I'll do some research and let you know

**Comment by indianpoptart** [comment]
I can assure you the app is safe. Not sure how much my word will go since I am some random person, but yeah, I'd never put any viruses in my app, I'll check in Android Studio, as well as a scan of my repository

**Comment by IzzySoft** [comment]
I didn't blame your app! In most cases it's either one of the libraries having an issue – or an update to studio components is fixing things. I just wanted to let you know before it pops up in a different way :wink:

**Comment by indianpoptart** [comment]
Just letting you know :) Don't want people to think I'm putting viruses. I greatly appreciate you bringing it to my attention. Hopefully, it's an easy fix! Might be that I have to update the ads library or something 😄

**Comment by IzzySoft** [comment]
Or simply leave out all the ad, analytics and Firebase stuff for the non-playstore version. Might even make it ligit for F-Droid then :wink:

**Comment by indianpoptart** [comment]
True, Although, I make sure all 3rd party features can be turned off. Ads are always on, unless disabled. Analytics, firebase, and fabric.io are all opt-in. Def going to work on making a non-playstore version. Do you know if there's a way in Android Studio to generate an apk without those features enabled? Or would I have to manually remove libraries and code. Thanks!

Also, I tried F-Droid a few months ago, was too complex to setup, but I love F-droid in general!

**Comment by IzzySoft** [comment]
What you're looking for are gradle flavors. I'm no dev, so I cannot give details on that – but that's what F-Droid often uses in such cases.

As you're already looking toward F-Droid: until you get the code/gradle-flavor ready, your app can already be [found here](https://apt.izzysoft.de/fdroid/index/apk/com.nikhilparanjape.radiocontrol) :wink:

**Comment by indianpoptart** [comment]
Sounds good, I'll try out gradle flavors. Thanks for putting my app in your repo! Looks great!

**Comment by indianpoptart** [comment]
Ayy, I fixed it

**Comment by IzzySoft** [comment]
Confirmed! No alert anymore for the latest release. May I ask who was the culprit? Arguing by the library list I'd say one of those nasty ad modules you thankfully removed?

**Comment by indianpoptart** [comment]
I think it was the ads, should be all gone now!, Except for some calls to disabling ads in Settings

Also updated all android support libraries to SDK 27

**Comment by IzzySoft** [comment]
Superb! So I guess we can close this? Unless you want to keep it open as reminder for some "after-work" that is?

**Comment by indianpoptart** [comment]
Yeah, all good. Thanks for all your help!

**Comment by IzzySoft** [comment]
Glad to! Thanks for the nice and fast fix!
